repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.3'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
